"""Add summary to Book

Revision ID: 35554d0da9d9
Revises: 755e6f5edc86
Create Date: 2025-06-03 13:15:20.730916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "35554d0da9d9"
down_revision = "755e6f5edc86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
