"""Add unique constraint on user_id, book_id to Review

Revision ID: 755e6f5edc86
Revises: 826603eb120e
Create Date: 2025-06-03 11:59:20.559212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "755e6f5edc86"
down_revision = "826603eb120e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_review_user_book", ["user_id", "book_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_constraint("uq_review_user_book", type_="unique")

    # ### end Alembic commands ###
