"""added: inventory_processed to Order to avoid double-decrementing stock

Revision ID: d1b4a86ff22a
Revises: f5f7de0d79bf
Create Date: 2025-06-04 06:28:37.758680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1b4a86ff22a"
down_revision = "f5f7de0d79bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "inventory_processed",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("FALSE"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("inventory_processed")

    # ### end Alembic commands ###
