"""added: inventory_restocked to Order to effect restock if order cancelled

Revision ID: f0b085baaca7
Revises: d1b4a86ff22a
Create Date: 2025-06-04 07:10:58.976512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0b085baaca7"
down_revision = "d1b4a86ff22a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "inventory_restocked",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("FALSE"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("inventory_restocked")

    # ### end Alembic commands ###
