"""Add summary to Book not Review

Revision ID: f5f7de0d79bf
Revises: 35554d0da9d9
Create Date: 2025-06-03 13:41:17.551767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5f7de0d79bf"
down_revision = "35554d0da9d9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.add_column(sa.Column("summary", sa.Text(), nullable=True))

    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True)
        )

    with op.batch_alter_table("books", schema=None) as batch_op:
        batch_op.drop_column("summary")

    # ### end Alembic commands ###
